# inherit from common
-include device/generic/safestrap-common/BoardConfigCommon.mk

# Kernel
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 4096
TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := omap4
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := pasteur

BOARD_HAS_LOCKED_BOOTLOADER := true
BOARD_RUNS_FIXBOOT := true

# TWRP
TARGET_RECOVERY_INITRC := device/generic/safestrap/init.rc
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
DEVICE_RESOLUTION := 1280x800
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
RECOVERY_TOUCHSCREEN_SWAP_XY := true
RECOVERY_TOUCHSCREEN_FLIP_Y := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_PROVIDES_INIT_RC := true
RECOVERY_SDCARD_ON_DATA := true

# MOTOROLA
TARGET_USE_CUSTOM_BATTERY_CAPACITY_PATH := "/sys/class/power_supply/battery/charge_counter"

