TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/sdcard-ext"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard-ext"
TW_DEFAULT_EXTERNAL_STORAGE := true
BOARD_USE_NO_DEVFS_SETUP := true
BOARD_SUPPRESS_EMMC_WIPE := true
HAVE_SELINUX := true
BOARD_DEFAULT_VIRT_SYSTEM_SIZE := 600
BOARD_DEFAULT_VIRT_CACHE_SIZE := 300
TW_CUSTOM_BATTERY_CAPACITY_FIELD := charge_counter
TW_INCLUDE_SPLASHMENU := true

TW_IGNORE_ZIP_ROOT_STORAGE_CHECK := true
