BOARD_USE_NO_DEVFS_SETUP := true
BOARD_SUPPRESS_EMMC_WIPE := true
HAVE_SELINUX := true
BOARD_DEFAULT_VIRT_SYSTEM_SIZE := 600
BOARD_DEFAULT_VIRT_CACHE_SIZE := 300
TW_CUSTOM_BATTERY_CAPACITY_FIELD := charge_counter
TW_ALWAYS_RMRF := true

